accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns =[
			path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
			path('logout/',auth_views.LogoutView.as_view(),name='logout'),
			path('signup/',views.SignUp.as_view(),name='signup'),
			path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password/password_reset.html'), name ='password_reset'),
			path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    		path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    		path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),
			]

users_template/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('logged_in/',views.LoggedIn.as_view(),name='logged_in'),
    path('logged_out/',views.LoggedOut.as_view(),name='logged_out'),
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

	def __str__(self):
		return '@{}'.format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

	class Meta:
		fields=('username','email','password1','password2')
		model=get_user_model()

	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		self.fields['username'].label='Display Name'
		self.fields['email'].label='Email Address'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms


# Create your views here.
class SignUp(CreateView):
	form_class=forms.UserCreateForm
	success_url=reverse_lazy('login')
	template_name='accounts/signup.html'

users_template/views.py
from django.views.generic import TemplateView

class LoggedIn(TemplateView):
	template_name='logged_in.html'

class LoggedOut(TemplateView):
	template_name='logged_out.html'


class HomePage(TemplateView):
	template_name='index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<div class="d-flex justify-content-center">	
	<div class="form-signin justify-content-center">	
		<form method="POST">
			<h3>Log In</h3>
			<hr>
			{% csrf_token %}
			{% bootstrap_form form %}
			<div style="margin-top: 2rem">
				<p>New user? <a href="{% url 'accounts:signup' %}">Click to sign up!</a></p>
				<p>Forgot your password? <a href="{% url 'accounts:password_reset' %}">Click to reset it</a></p>
			</div>
			<input type="submit" class="btn btn-primary" style="margin-top: 1rem" value="Login">			
		</form>	
	</div>
</div>

{% endblock content %}

accounts/templates/accounts/password/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}
<div class="d-flex justify-content-center">	
    <div class="form-signin justify-content-center" style="max-width: 600px;">
        <h2 class="font-weight-bold mt-3">Reset Password</h2>
        <hr>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/password/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container p-4">
    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
    <hr>
    <p>Your password has been set. You may go ahead and log in now.</p>                 
    <a href="{% url 'accounts:login' %}" class="btn btn-primary">Log in</a>
</div>

{% endblock content %}

accounts/templates/accounts/password/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}

<div class="d-flex justify-content-center">	
	<div class="form-signin justify-content-center" style="max-width: 600px;">
        <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
        <hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/password/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Password reset sent</h2>
        <hr>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
    </div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}

<div class="d-flex justify-content-center">	
	<div class="form-signin justify-content-center" style="max-width: 600px;">	
		<form method="POST">
			<h3>Sign up</h3>
			<hr>
			{% csrf_token %}
			{% bootstrap_form form %}
			<input type="submit" class="btn btn-primary" style="margin-top: 1rem" value="Sign Up">
		</form>	
	</div>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>Leistungsverzeichnis</title>
        <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static "bootstrap-5.2.0-dist/css/bootstrap.css" %}">
    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="{% static "bootstrap-icons-1.10.2/bootstrap-icons.css" %}">

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet">

    <!-- custom css - has to be as the last one from styles -->
    <link rel="stylesheet" type="text/css" href="{% static "leistungsverzeichnis/css/master.css" %}">



</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark techfont">
          <div class="container-fluid">
            <a class="navbar-brand bigbrand" href="{% url 'home' %}">Leistungsverzeichnis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">Explorer</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                         <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="#">Edit 1</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Edit 2</a>
                            </li>
                        
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                         </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                    
                </ul>
                  
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                                        
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Sign Up</a>
                        </li>
                    {% endif %}                  
                </ul>
            </div> 
        </div>
    </nav>
    <div class="container table-content">     
        {% for message in messages %}    
            <div class="alert alert-{{ message.tags }}">
                <a class="close" href="#" data-dismiss="alert"></a>
                {{ message }}
            </div>
        {% endfor %}

        {% block content %}

        {% endblock %}     
    </div>

</body>

<!-- js -->
<script src={% static "bootstrap-5.2.0-dist/js/bootstrap.bundle.min.js" %}></script>
<script src="{% static "leistungsverzeichnis/js/stylings.js" %}" type="text/javascript"></script>


</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
	<h1>Welcome in This app!</h1>
{% endblock content %}

templates/logged_in.html
{% extends "base.html" %}
{% block content %}
	<h1>You are logged in!</h1>
{% endblock content %}

templates/logged_out.html
{% extends "base.html" %}
{% block content %}
	<h1>Thanks for visiting, come back soon!</h1>
{% endblock content %}